import { Inter } from "next/font/google";
import Link from "next/link";
import Image from "next/image";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<header className="header-aera py-4">
					<div className="container mx-auto px-4">
						<div className="header__wrp flex items-center justify-between gap-10">
							<Link className="logo inline-block" href="/">
								<Image
									src="/assets/images/logo/logo.svg"
									width={190}
									height={61}
									alt="Picture of the author"
								/>
							</Link>
							<ul className="nav flex gap-5 justify-center">
								<li className="nav-item">
									<Link
										className="nav-link hover:text-green-700 transition-all duration-500 p-4 inline-block font-medium"
										href="/"
									>
										Home
									</Link>
								</li>
								<li className="nav-item">
									<Link
										className="nav-link hover:text-green-700 transition-all duration-500 p-4 inline-block font-medium"
										href="/about"
									>
										About
									</Link>
								</li>
								<li className="nav-item">
									<Link
										className="nav-link hover:text-green-700 transition-all duration-500 p-4 inline-block font-medium"
										href="/team"
									>
										Team
									</Link>
								</li>
								<li className="nav-item">
									<Link
										className="nav-link hover:text-green-700 transition-all duration-500 p-4 inline-block font-medium"
										href="/blog"
									>
										Blogs
									</Link>
								</li>
								<li className="nav-item">
									<Link
										className="nav-link hover:text-green-700 transition-all duration-500 p-4 inline-block font-medium"
										href="/contact"
									>
										Contact
									</Link>
								</li>
							</ul>
              <button className="px-10 py-4 inline-block font-medium text-white bg-green-700 rounded-md">Login</button>
						</div>
					</div>
				</header>

				{children}
			</body>
		</html>
	);
}
